# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.
# ------------------------------------------------------------

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: env-secret
  namespace: mesoid
spec:
  type: secretstores.local.env
  version: v1
  initTimeout: 1m
  metadata:
    - name: redisHost
      value: "dapr-redis-svc:45454"
    - name: redisPassword
      value: "1234"
    - name: keyPrefix
      value: "{uuid}"
